[package]
name = "browser-eng-ch1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hw_uri = { path = "../../crates/hw_uri" }
openssl = "0.10"
